// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpGAjzC86jeY2tyVYHEQj8zGPykw_tODs',
    appId: '1:332556439035:ios:45f42fa31b1ac99a7d0f5e',
    messagingSenderId: '332556439035',
    projectId: 'hakgulsdiary',
    storageBucket: 'hakgulsdiary.firebasestorage.app',
    iosBundleId: 'com.example.hakgulsdaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYUIFZtMsM7X2sk7NAugwNe19OvJfR8Io',
    appId: '1:332556439035:web:3a82f562aab1ba947d0f5e',
    messagingSenderId: '332556439035',
    projectId: 'hakgulsdiary',
    authDomain: 'hakgulsdiary.firebaseapp.com',
    storageBucket: 'hakgulsdiary.firebasestorage.app',
    measurementId: 'G-R57F2F82QL',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYUIFZtMsM7X2sk7NAugwNe19OvJfR8Io',
    appId: '1:332556439035:web:3a82f562aab1ba947d0f5e',
    messagingSenderId: '332556439035',
    projectId: 'hakgulsdiary',
    authDomain: 'hakgulsdiary.firebaseapp.com',
    storageBucket: 'hakgulsdiary.firebasestorage.app',
    measurementId: 'G-R57F2F82QL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGAjzC86jeY2tyVYHEQj8zGPykw_tODs',
    appId: '1:332556439035:ios:45f42fa31b1ac99a7d0f5e',
    messagingSenderId: '332556439035',
    projectId: 'hakgulsdiary',
    storageBucket: 'hakgulsdiary.firebasestorage.app',
    iosBundleId: 'com.example.hakgulsdaily',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr45-7_CuOzFW-aUHfALyOkZvQWSWM5og',
    appId: '1:332556439035:android:c32c8573c610003d7d0f5e',
    messagingSenderId: '332556439035',
    projectId: 'hakgulsdiary',
    storageBucket: 'hakgulsdiary.firebasestorage.app',
  );

}